### ISSUE TITLE
Pre-generation counter maths appears to be incorrect

### ISSUE THREAD

**Issue by DrHenchman** [DrHenchman/uhc-pack#29]
There has been a long outstanding bug where the Done chunks seems to exceed the Total chunks by the end of the pre-generation. Its likely that the maths is off by one somewhere

**Comment by PhotonBursted** [comment]
I think the issue is that the check for being "done" is done too late, or the check is too strict.
By the time the check comes around the X coordinate has already reset, which means that - even though the Z coordinate indicates the pregen operation is done - the datapack thinks it should go another stretch

**Comment by PhotonBursted** [comment]
...nope, that does not seem to be it, further sciencing underway :P

**Comment by PhotonBursted** [comment]
Ah, right, `X` always starts at 0, then continues uptill **and including** the border. This means it does one teleport too much in the X direction for every step in the Z direction, which is where the off-by-one would come from
